"""init

Revision ID: 04a91875eb95
Revises: 
Create Date: 2026-03-02 11:36:36.853219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a91875eb95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('inat_user_id', sa.Integer(), nullable=False),
    sa.Column('inat_username', sa.String(length=255), nullable=True),
    sa.Column('inat_dna_field_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_lists_inat_user_id'), 'observation_lists', ['inat_user_id'], unique=False)
    op.create_index(op.f('ix_observation_lists_title'), 'observation_lists', ['title'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inat_observation_id', sa.Integer(), nullable=False),
    sa.Column('taxon_name', sa.String(length=255), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('inat_url', sa.String(length=512), nullable=False),
    sa.Column('dna_field_value', sa.String(length=255), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['observation_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'inat_observation_id', name='uq_observation_list_inat_id')
    )
    op.create_index(op.f('ix_observations_inat_observation_id'), 'observations', ['inat_observation_id'], unique=False)
    op.create_index(op.f('ix_observations_list_id'), 'observations', ['list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_list_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_inat_observation_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_observation_lists_title'), table_name='observation_lists')
    op.drop_index(op.f('ix_observation_lists_inat_user_id'), table_name='observation_lists')
    op.drop_table('observation_lists')
    # ### end Alembic commands ###
