"""add_taxon_filter_and_limits

Revision ID: 0d5d939079ab
Revises: bbb6b9f80d9d
Create Date: 2026-03-02 15:05:21.690948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5d939079ab'
down_revision = 'bbb6b9f80d9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation_lists', sa.Column('taxon_filter', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observation_lists', 'taxon_filter')
    # ### end Alembic commands ###
