"""add_observation_fields

Revision ID: bbb6b9f80d9d
Revises: 04a91875eb95
Create Date: 2026-03-02 13:21:36.520209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb6b9f80d9d'
down_revision = '04a91875eb95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('species_guess', sa.String(length=255), nullable=True))
    op.add_column('observations', sa.Column('scientific_name', sa.String(length=255), nullable=True))
    op.add_column('observations', sa.Column('common_name', sa.String(length=255), nullable=True))
    op.add_column('observations', sa.Column('user_name', sa.String(length=255), nullable=True))
    op.alter_column('observations', 'taxon_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('observations', 'dna_field_value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('observations', 'dna_field_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('observations', 'taxon_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('observations', 'user_name')
    op.drop_column('observations', 'common_name')
    op.drop_column('observations', 'scientific_name')
    op.drop_column('observations', 'species_guess')
    # ### end Alembic commands ###
